### ISSUE TITLE
Why the PathBase?

### ISSUE THREAD

**Issue by jhgbrt** [bleroy/FluentPath#5]
I'm probably missing something, but I don't understand the reasoning of having `PathBase<T>`, since there is only one derived class (`Path`)?

**Comment by bleroy** [comment]
Fair question. The idea, originally, was that you could inherit from Path (or as it turns out PathBase) and make versions that would for example implement different type systems, without needing to re-implement everything. But here's the thing: fluent APIs don't play well with inheritance, because methods that return an instance of the type need to return the derived type and not the base. So it needs to be generic so the return type can be the type parameter. That never really materialized however, so it doesn't really have a purpose as tings stand today. In fact, it took about ten minutes to make a version without the base class: https://github.com/bleroy/FluentPath/tree/no-base-class Functionally, and in terms of public API surface, pretty much nothing changes.
